### ISSUE TITLE
Could you please explain what you did in your hash implementation?

### ISSUE THREAD

**Issue by LukeDias42** [anirban-s/data-structures-and-algorithms#1]
I am following the same course as you are and using your solutions when I am stuck, and I got relly stuck on that implementations. Why did you think of creating another class called Node? How does that even work in the code, I thought it was a little confusing..

**Comment by anirban-s** [comment]
Here, I created the Node class to hold the value of key and value of the object as hashtable object has key and value. It helps me to create a list of Node object in my hashtable implementation.
