### ISSUE TITLE
Again abou the Hash implementation.

### ISSUE THREAD

**Issue by LukeDias42** [anirban-s/data-structures-and-algorithms#2]
I was reading about inheriting from List<T>, and apparently it is not a very good thing to do unless you are trying to build a mecahnism, which I am not sure if that is what you had in mind. Anyway, what I did was simply wrapped a List inside the class.
https://stackoverflow.com/questions/21692193/why-not-inherit-from-listt
Take a look at the question and comments, they are very enlightening, I think.

**Comment by anirban-s** [comment]
Thanks for sharing.
